### ISSUE TITLE
line breaking a set display

### ISSUE THREAD

**Issue by florianschanda** [Spivoxity/fuzz#1]
Hi,

I have the following file which typesets just fine:
```
\documentclass{article}
\usepackage{z}
\begin{document}
\begin{axdef}
  foo : \nat \fun \nat
\where
  foo = \{ 1 \mapsto 2, 2 \mapsto 3 \}
\end{axdef}

\begin{axdef}
  bar : \nat \fun \nat
\where
  bar = \{ \\   % this is line 13
    \t1 1 \mapsto 2, \\
    \t1 2 \mapsto 3 \\
  \}
\end{axdef}

\end{document}
```

However the definition of bar causes a problem for fuzz:
```
"foo.tex", line 13: Syntax error at "\\" or "\also"
```

Is there a better way to do this?

**Comment by Spivoxity** [comment]
Sorry, those are the rules of Z: newlines are ignored only before and after certain 'infix' symbols, one of them being a comma.  So you can break your set display in the middle or before the = sign, but you can't have line breaks inside the braces at the beginning or end.

If I were designing the rules of Z now, I might make a different and more permissive set of rules.  But then again, if I were choosing a specification language now, it would look less like set theory and more like functional programming.  And sequences would be indexed starting at 0!

The choices I made at the time were partly determined by the informal conventions my colleagues were using, and partly by the search for a fairly simple set of rules we thought we could live with.  If you want to make your own, syntactically more permissive, dialect of Z, then the source of fuzz is there for you to use as a starting point.

I'm closing the issue now with a "won't fix".  It is 35 years too late.

**Comment by florianschanda** [comment]
Right, thanks for confirming I wasn't missing something obvious.

As to using the source; already doing so, thanks so much for writing this and releasing it :)

I do have a fork/update of the latex template to make it not use any metafont glyphs (as it makes it awkward to use these days), I  instead use existing symbols from e.g. amssymb and hand-drawing the rest using tikz.

https://github.com/florianschanda/pzt/blob/master/latex/z.sty

If you're interested I could clean it up and prepare a PR; or just send you a patch file instead.
