### ISSUE TITLE
configuration parameters

### ISSUE THREAD

**Issue by moar82** [Spivoxity/fuzz#2]
Any examples of the config stuff parameters in the make file?
I am using Ubuntu.

prefix = @prefix@
exec_prefix = @exec_prefix@
libdir = @libdir@
VERSION = @PACKAGE_VERSION@
AWK = @AWK@

Thanks.

**Comment by Spivoxity** [comment]
I've updated the README with a short hint how to use the more recently provided 'configure' script. -- Mike

**Comment by moar82** [comment]
Thanks Mike for your quick response.  It works now until reaching the following line of the MakeFile:
`flex -ozscan.c zscan.l
make[1]: flex: Command not found
Makefile:68: recipe for target 'zscan.c' failed`
So, I guess I need to install flex to solve this dependency issue.  

I wonder if it is possible for you to share the full list of dependencies?  Indeed, my idea is to create a public docker container for fuzz, so anyone can profit of it without the burden of setting up the environment themselves.  That will help not only Unix/Linux users but  windows and other platforms.
TIA.  Rodrigo.

**Comment by moar82** [comment]
I've just want to give an update.  To fix the aforementioned error I installed **gawk**, and that solved the issue.
